# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 0) do

  create_table "engine_schema_info", :id => false, :force => true do |t|
    t.column "engine_name", :string
    t.column "version",     :integer
  end

end
